manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: barbellboards
      url-base: https://github.com/barbellboards
  projects:
    - name: zmk
      repo-path: Rollow-ZMK
      remote: barbellboards
      revision: barbellboards/rollow
      import: app/west.yml
  self:
    path: config
